#!/bin/sh

# Change `style.css` or `style.min.css` to whatever you would like your compiled
# stylesheet to be called. Do not rename `style.scss` or alter references to it.

# No minification
sass --watch --sourcemap styles/sass/main.scss:styles/main.css --style expanded 

# sass --watch styles/sass/main.scss:styles/main.min.css --style compressed

exit 0